# Generated by Django 4.2.19 on 2025-03-05 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('account_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=30)),
                ('category', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions_account_id', to='account.account')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
